services:
  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    shm_size: 128mb
   #  added a health check which can be used by depends on as it starts db
    healthcheck:
      # passsed the -d parameter so the correct db name can be set which is different from the username
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  sub-app: 
    build: .
    ports: 
      # define the ports we are running it on
      - "8082:8082"
    environment:
      # instead of @localhost we use @db
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
    # this ensures that db is started before the app
    depends_on:
      db: 
        condition: service_healthy

volumes:
  postgres_data: 
