from fastapi import FastAPI, HTTPException,status, Depends
from pydantic import BaseModel, Field
import uuid # assigning unique ids to each entry in the table
from typing import Optional # we use this for are patch requests, we set all the attr as optional so the user can modify only what they need to
from models import Subscription, User # the subs class from models.py
from db import Base, engine, get_db # the Base class alongside engine from db.py
from sqlalchemy.orm import Session
from schemas import UserCreate, UserOut
from auth import create_access_token, get_current_user, hash_password, verify_password
from fastapi.security import OAuth2PasswordRequestForm
from datetime import date

Base.metadata.create_all(bind=engine) # without bind=engine, we only will have the python objects containing the table layouts, bind=engine provides
# the connection with the information about the table layouts that it needs.

app = FastAPI() # create an object of the type

@app.get("/")
def read_root():
	return {"Hey" : "Working"}

# PYDANTIC MODEL CLASSES (PROVIDE INPUT AND OUTPUT SHAPE)

class Subscriptions(BaseModel): # the base class that is used for get/post/delete as we modify/add all the attributes at once instead of specific ones
	name: str
	cost: float	
	billing_cycle: str
	description: str
	renewal_time: date = Field(default_factory=date.today) # default factory runs the function at produces a fresh value for each each time
	# if a value depends on randommness, time or a mutable object default factory is needed to be used.

class SubscriptionsUpdate(BaseModel): # this class is introduced as there will be a difference in the input/output shape for when we add a patch request
	# the way a patch request works is that it only changes specific attr, instead of all, which means we can't just overwrite everything instead only
	# certain attr that the user wants to, for that to work we need to ensure that the attr are set to None by default so only set attr can be changed
	name: Optional[str] = None
	cost: Optional[float] = None	
	billing_cycle: Optional[str] = None
	description: Optional[str] = None
	renewal_date: Optional[date] = None 
	model_config = {"from_attributes": True}

class SubscriptionOut(Subscriptions):
	id: uuid.UUID
	model_config = {"from_attributes": True} # this allows pydantic model to read objects from SQLalchemy instead of just python dict


class SubscriptionDelete(SubscriptionOut): # as we also need id which SubOut has not the main Sub class
	message: str
	model_config = {"from_attributes": True}

class Token(BaseModel): # defining a shape for the Token
	access_token: str
	token_type: str = "bearer" # conventional value to use, it tells the client to attach the token to the authorization header as Bearer <token>	


# ========================= Helper Function

def get_subscription_or_404(id: uuid.UUID, db: Session, curr_user : User) -> Subscription: # I have created a  helper function to reduce redundancy in the code, as this part is used in almost all the requests
	# returns an object of type Subscription (SQLalchemy type)
	result = db.query(Subscription).filter(Subscription.id == id,  Subscription.owner_id == curr_user.id).first() # this fetches the first row that meets the condition
	# we use the db.query() method to find the data and filter is based on if id == id, then return the first row that meets the filter criteria
	# The added condition checks if the user logged in is the same user fetching the data, if the id's are different 404 is raised automatically
	if result:
		return result
	else: 
		raise HTTPException(status_code= status.HTTP_404_NOT_FOUND, detail= "Id not found!")



@app.post("/subscriptions", status_code = status.HTTP_201_CREATED, response_model = SubscriptionOut)
# its important to note that a response model strictly binds what the output schema will be for the request type
def write_subscriptions(sub: Subscriptions, db: Session = Depends(get_db), curr_user: User = Depends(get_current_user)):
	'''
	Depends() is the core function for dependency injection, it manages the automatic lifecycle for shared resources, in this case
	the db session. It is able to extract yielded session objects, injects into route parameter, and guarantees cleanup. It shifts
	the burden of resource lifetime management from the user to the framework instead. 
	'''	
	user_data = sub.model_dump() # the newer version of changing a model obj into a dict 
	# removed id generation from the function as it is being generated by default in the Subscription Class (model.py)	
	user_data["owner_id"] = curr_user.id
	data_insertion = Subscription(**user_data) # allows us to map the user-data onto the Subs class fields (DB Fields directly)
	
	db.add(data_insertion)
	db.commit()
	db.refresh(data_insertion)
	''' 
	instead of 	return {"id": id, "name": sub.name, "cost": sub.cost, "billing_cycle": sub.billing_cycle, "description":sub.description} we use dict unpacking 
	that makes the code easier to read as we already did turn the obj into a dict using the model.dump function
	'''
	return data_insertion 


# the shape of the data is a template that the return data has to fit in, any access data is filtered out/removed 
@app.get("/subscriptions/{id}", response_model = SubscriptionOut) # {id} is the path parameter, anything inside the {} is treated as a variable by fastapi
def get_subscriptions(id: uuid.UUID, db: Session = Depends(get_db), curr_user: User = Depends(get_current_user)): # we make sure that the id is mapped currently to its type, what this does is that fastapi will parse the inputs into
# a UUID object and reject requests that don't fit the UUID shape 
	data_get = get_subscription_or_404(id, db, curr_user) # we simply pass the id into the function to get the entry that we are looking for  
	return data_get # returns us an object with the 

@app.delete("/subscriptions/{id}", response_model = SubscriptionDelete) # delete
def delete_subscriptions(id: uuid.UUID, db: Session = Depends(get_db), curr_user: User = Depends(get_current_user)):
	deleted_data = get_subscription_or_404(id, db, curr_user)
	clean_data = SubscriptionOut.model_validate(deleted_data).model_dump(exclude={"id"}) # this will return a python dict 
	# model_validate converts the data into a pydantic model and model_dump then into a dict
	db.delete(deleted_data) # we use .delete() method to remove the specific row
	db.commit()

	return {"message": f"Subscription '{clean_data['name']}' has been deleted", "id": id, **clean_data}
	# Subscription 'Netflix' has been deleted, this is how it will look like, this could have been made simplier if we didn't add the name

@app.patch("/subscriptions/{id}", response_model = SubscriptionOut) # patch
def update_subscriptions(id: uuid.UUID, update_data: SubscriptionsUpdate, db: Session = Depends(get_db), curr_user: User = Depends(get_current_user)): # we will need to convert the pydantic model into a dict hence the parameters
	existing_data = get_subscription_or_404(id, db, curr_user)
	new_data = update_data.model_dump(exclude_unset=True)
	# exclude_unset only includes the fields that the client explicitly sent in the request

	for key, val in new_data.items():
		setattr(existing_data, key, val) # settattr bypasses the conventional dot notation limitations. As in this instance, we don't know the attr "key" has
		# but using settatrr we can simply get that column name on runtime and modify the value

	db.commit()
	db.refresh(existing_data)

	return existing_data

# ========================== Register

@app.post("/register", response_model=UserOut) # we use the userout shape to ensure that pass never gets seen
def add_user(user: UserCreate, db: Session = Depends(get_db)):
	user_data = user.model_dump() # convert the python obj into a dict
	hashed_password = hash_password(user_data["password"]) # we pass the password for hashing

	data_insertion = User(
		username=user_data["username"],
		hashed_password=hashed_password
		)

	db.add(data_insertion)
	db.commit()
	db.refresh(data_insertion)

	return data_insertion

@app.post("/login", response_model=Token)
def login(form_data: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):
	result = db.query(User).filter(User.username == form_data.username).first() # fetch the results if user matches

	if result and verify_password(form_data.password, result.hashed_password): 

		return Token ( # we create a Token shape to return and match with the response model
			access_token= create_access_token(data={"sub":result.username}),
			token_type= "bearer" # bearer follows standard compliance, interoperability and clear HTTP semantics
		)

	else:
		raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Incorrect Credentials")