from fastapi import FastAPI, HTTPException,status, Depends
from pydantic import BaseModel
import uuid # assigning unique ids to each entry in the table
from typing import Optional # we use this for are patch requests, we set all the attr as optional so the user can modify only what they need to
from models import Subscription # the subs class from models.py
from db import Base, engine, get_db # the Base class alongside engine from db.py
from sqlalchemy.orm import Session

Base.metadata.create_all(bind=engine) # without bind=engine, we only will have the python objects containing the table layouts, bind=engine provides
# the connection with the information about the table layouts that it needs.

app = FastAPI() # create an object of the type

@app.get("/")
def read_root():
	return {"Hey" : "Working"}

class Subscriptions(BaseModel): # the base class that is used for get/post/delete as we modify/add all the attributes at once instead of specific ones
	name: str
	cost: float	
	billing_cycle: str
	description: str

class SubscriptionsUpdate(BaseModel): # this class is introduced as there will be a difference in the input/output shape for when we add a patch request
	# the way a patch request works is that it only changes specific attr, instead of all, which means we can't just overwrite everything instead only
	# certain attr that the user wants to, for that to work we need to ensure that the attr are set to None by default so only set attr can be changed
	name: Optional[str] = None
	cost: Optional[float] = None	
	billing_cycle: Optional[str] = None
	description: Optional[str] = None
	model_config = {"from_attributes": True}

class SubscriptionOut(Subscriptions):
	id: uuid.UUID
	model_config = {"from_attributes": True} # this allows pydantic model to read objects from SQLalchemy instead of just python dict


class SubscriptionDelete(SubscriptionOut): # as we also need id which SubOut has not the main Sub class
	message: str
	model_config = {"from_attributes": True}

def get_subscription_or_404(id: uuid.UUID, db: Session) -> Subscription: # I have created a  helper function to reduce redundancy in the code, as this part is used in almost all the requests
	# returns an object of type Subscription (SQLalchemy type)
	result = db.query(Subscription).filter(Subscription.id == id).first() # this fetches the first row that meets the condition
	# we use the db.query() method to find the data and filter is based on if id == id, then return the first row that meets the filter criteria
	if result:
		return result
	else: 
		raise HTTPException(status_code= status.HTTP_404_NOT_FOUND, detail= "Id not found!")


@app.post("/subscriptions", status_code = status.HTTP_201_CREATED, response_model = SubscriptionOut)
# its important to note that a response model strictly binds what the output schema will be for the request type
def write_subscriptions(sub: Subscriptions, db: Session = Depends(get_db)):
	
	user_data = sub.model_dump() # the newer version of changing a model obj into a dict 
	# removed id generation from the function as it is being generated by default in the Subscription Class (model.py)	
	data_insertion = Subscription(**user_data) # allows us to map the user-data onto the Subs class fields (DB Fields directly)
	
	db.add(data_insertion)
	db.commit()
	db.refresh(data_insertion)
	''' 
	instead of 	return {"id": id, "name": sub.name, "cost": sub.cost, "billing_cycle": sub.billing_cycle, "description":sub.description} we use dict unpacking 
	that makes the code easier to read as we already did turn the obj into a dict using the model.dump function
	'''
	return data_insertion 


# the shape of the data is a template that the return data has to fit in, any access data is filtered out/removed 
@app.get("/subscriptions/{id}", response_model = SubscriptionOut) # {id} is the path parameter, anything inside the {} is treated as a variable by fastapi
def get_subscriptions(id: uuid.UUID, db: Session = Depends(get_db)): # we make sure that the id is mapped currently to its type, what this does is that fastapi will parse the inputs into
# a UUID object and reject requests that don't fit the UUID shape 
	data_get = get_subscription_or_404(id, db) # we simply pass the id into the function to get the entry that we are looking for  
	return data_get # returns us an object with the 

@app.delete("/subscriptions/{id}", response_model = SubscriptionDelete) # delete
def delete_subscriptions(id: uuid.UUID, db: Session = Depends(get_db)):
	deleted_data = get_subscription_or_404(id, db)
	clean_data = SubscriptionOut.model_validate(deleted_data).model_dump(exclude={"id"}) # this will return a python dict 
	# model_validate converts the data into a pydantic model and model_dump then into a dict
	db.delete(deleted_data) # we use .delete() method to remove the specific row
	db.commit()

	return {"message": f"Subscription '{clean_data['name']}' has been deleted", "id": id, **clean_data}
	# Subscription 'Netflix' has been deleted, this is how it will look like, this could have been made simplier if we didn't add the name

@app.patch("/subscriptions/{id}", response_model = SubscriptionOut) # patch
def update_subscriptions(id: uuid.UUID, update_data: SubscriptionsUpdate, db: Session = Depends(get_db)): # we will need to convert the pydantic model into a dict hence the parameters
	existing_data = get_subscription_or_404(id, db)
	new_data = update_data.model_dump(exclude_unset=True)
	# exclude_unset only includes the fields that the client explicitly sent in the request

	for key, val in new_data.items():
		setattr(existing_data, key, val) # settattr bypasses the conventional dot notation limitations. As in this instance, we don't know the attr "key" has
		# but using settatrr we can simply get that column name on runtime and modify the value

	db.commit()
	db.refresh(existing_data)

	return existing_data


